language: ruby
cache: bundler
rvm:
- 2.2.2
addons:
  apt:
    packages:
    - python-sphinx
before_install: gem install bundler -v 1.11.2
install:
- bundle install --jobs=3 --retry=4
- git config --global user.name  "Travis CI"
- git config --global user.email "pdc@product-definition-center.com"
- export REPO_URL_GITHUB="https://$GH_TOKEN@github.com/$GH_REPO.git"
- export PRONTO_GITHUB_ACCESS_TOKEN=$GH_TOKEN
script:
- bundle exec rake test
- >
  if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    bundle exec pronto run -f github_pr -c origin/${TRAVIS_BRANCH}
  fi
-after_success:
#-- >
# -  [ "$TRAVIS_BRANCH" = "master" ] &&
# -  [ "$TRAVIS_PULL_REQUEST" = "false" ] &&
# -    make -C docs/ setup_gh_pages generate deploy

# JUST FOR DEMO
- make -C docs/ setup_gh_pages generate deploy
env:
  global:
  - GH_REPO="ycheng-aa/pdc-ruby-gem"
  - PRONTO_PULL_REQUEST_ID=${TRAVIS_PULL_REQUEST}
  - secure: iHgoCpvnHrUxQcCJJbQUlXt5VgjI2BZ7M1CMwAjKNukZ95mBKK0ABJA3j1IpLL4Eeypyq08/GUfJlq9d7sCF5VVgMXkhr0q0O/JDqa+gHX79/syU5kP91m9PXmpCW3myMP4szHydUoFoFAQc3zKlbDEtx359bPn3/wdOAGYJR8bkg5selsrdNJmCwXnCIAsWm3Pg53GnKDrTM9sIiqClaP60Pdp6OBPfdDDHLu5kSepFMut0eeXRXf65iifss1FqDxJdvbEiWLJtgXU5xdnbnhnh687rSCpxoX5gN5uc5L2DhYwrAnnHsT6aMtqi4wwxs4K56ilME0rwPD5k70I3h5Uj3ukMRK3IGxoblwi0FYKzLw+gLs2m2RExIicdo1o1Vc+DD2JbNtrLzFboX+oaeHowQpedD6BZsjt/KvO0huzOjfYlPNBde4nfddJ+w/dCRLnP3U7agEBm1hg/Erx0pCOFVutTDpMesPBM9AZzUcEj2jq/VFvKyPHbHvD1x1ZXnGWad15osMumYrEYUzbFy+f0fD9YiwsQMCxOeywelsmJNS0n8c8YkDy7t+JXxlMwGn6tF3bskS+qo4JMWvTHlVN7obnUJNB69IWFAAAA0klNcBtPQ3zgYgp9Kv9l/GBUBCzLI32XidZ4FGnAjAGDVOy4apqxCvXmOV5tkYoGwGU=
